export { Card, CardFoot } from './Card'
export type { CardProps } from './Card'
export { Footer } from './Footer'
export type { FooterProps } from './Footer'
export { Header } from './Header'
export type { HeaderProps } from './Header'
export { OrgMark } from './OrgMark'
export { Page } from './Page'
export type { PageProps } from './Page'
